---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    auto-config.enabled: false
  security:
    mock:
      users:
        - name: ivan
          password: 123456
          additional:
            firstName: ivan
            lastName: danin
            email: ivan.danin
          roles:
            - Administrators
          additional:
            firstName: ivan
            lastName: danin
            email: ivan.danin
